language: node_js
node_js:
- 10.8.0
cache:
  directories:
  - node_modules
before_install:
- export TZ='Asia/Shanghai'
- npm i -g npm@6.4.1 -g
- npm install npm@6.4.1 -g
- npm install hexo-cli -g
install:
- npm install
script:
- hexo clean
- hexo generate
- hexo d
after_script:
  - git clone https://${GH_REF} .deploy_git  # GH_REF是最下面配置的仓库地址
  - cd .deploy_git
  - git checkout master
  - cd ../
  - mv .deploy_git/.git/ ./public/ 
  - cd ./public
  - git config user.name "xiang578"
  - git config user.email "xiang578@foxmail.com"
  - git add .
  # - git commit -m "Deploy at $(date +"%Y-%m-%d %T")"
  - git commit -m "Travis CI Auto Builder at `date +"%Y-%m-%d %H:%M"`"
  # Github Pages
  - git push --force --quiet "https://${CI_TOKEN}@${GH_REF}" master:master 
  # Coding Pages
  # - git push --force --quiet "https://xiang578:${Coding_TOKEN}@${CO_REF}" master:master

branches:
  only:
  - hexo

env:
 global:
   - GH_REF: github.com/xiang578/xiang578.github.io
   - SecretId: ${SecretId}
   - SecretKey: ${SecretKey}
